"""initial

Revision ID: 5e1c8d75827e
Revises: 
Create Date: 2026-01-17 20:00:51.796386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e1c8d75827e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('grid_size', sa.Integer(), nullable=False),
    sa.Column('grid_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('across_clues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('down_clues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clue_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic', 'publish_date', name='uq_topic_publish_date')
    )
    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.create_index('idx_topic_date', ['topic', 'publish_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_puzzles_publish_date'), ['publish_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_puzzles_topic'), ['topic'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puzzles_topic'))
        batch_op.drop_index(batch_op.f('ix_puzzles_publish_date'))
        batch_op.drop_index('idx_topic_date')

    op.drop_table('puzzles')
    # ### end Alembic commands ###
